### ISSUE TITLE
Feature request for box relocation

### ISSUE THREAD

**Issue by franckflo** [sanguaire/fast-dice-box#1]
Hi,

It's a lovely concept, thanks for working on this. I'm having a bit of problem with its location though, as it seems it is hidden by the sidebar (even if I minimize the sidebar, see screenshot).

<img width="64" alt="Fast dice box" src="https://user-images.githubusercontent.com/80221412/209417875-cfb9fd1b-bc4e-43a4-b956-085a3ed77b80.png">

It would be nice if the position (an why not the orientation: horizontal vs vertical) could be adjusted in the settings.

Potential fixes:
-- have a settings to pick the top-right corner coordinates for the box (showing the current one so it's easier to adjust)
-- have a setting to choose between vertical and horizontal orientation.

Of course it would be even easier if we could have a drag-drop handle on the box itself so we could adjust it quickly (and if it saved those settings as default for next session). 

Another cool settings would be to have several box sizes to choose from.

Thanks!

**Comment by pesky-wobbit** [comment]
Second this request! Even just an option for "upper right" and "lower right".

**Comment by sanguaire** [comment]
I make the box draggable. Hope this helps 😉
