### ISSUE TITLE
Changing location of roll mode icons while maximized refreshes dice bar with most of it offscreen

### ISSUE THREAD

**Issue by dstein766** [sanguaire/fast-dice-box#11]
Fast dice box 0.10.2

My initial starting position is lower right, opening upward. (my saved x is roughly 730px)
I open the dice window.  The dice bar renders upward, with the top of the full window now around 200px (actually location unknown, just throwing in a number as a placeholder).  The point is that the opened dice window is several hundred pixels in height.
Click on the white UI arrow (which shows just under the dice roll mode selector) to flipflop the dice roll mode selection to the OTHER side of the column.

EXPECTED BEHAVIOR: opened dice bar remains in same position, dice roll mode selection icons move to other side of dice bar.
ACTUAL BEHAVIOR: opened dice bar re-renders, with top returned to starting position (i.e. 730px)...so the d20 icon appears at 730,y and the rest of the dice bar is underneath that...meaning that most of the dice bar is off the bottom of the screen and inaccessible.  If I refresh screen the unopened dice bar renders at 730,y as expected and I can re-open it normally.

Dice bar opened from initial position in lower right.  The arrow to flip location of roll mode icons highlighted:
![FxkSeAgPAV](https://github.com/sanguaire/fast-dice-box/assets/24942951/139a8ae1-2d76-4d13-bbdb-3afe3fed9710)

After flipping, the opened dice bar has be repainted but used the initial top position (meant for the UNOPENED dice bar) - so most of the dice bar, including the minimize control, is offscreen.  Have to refresh display to get back to useable (but unopened) dice bar.
![KdEZ5AEIsp](https://github.com/sanguaire/fast-dice-box/assets/24942951/ee0a2d58-d0c7-4667-b07c-734d829ef25d)

**Comment by sanguaire** [comment]
I checked it, but I have no clue why there is this behavior. After reloading foundry the box works as expected till the position of the roll modes change. 

So as a workaround:
Reload foundry after the roll mode box changes the position.

**Comment by sanguaire** [comment]
Fixed in v0.10.3
