### ISSUE TITLE
V11 compatibility

### ISSUE THREAD

**Issue by PhlegmaTREEc** [sanguaire/fast-dice-box#12]
Hello, this should be compatible with V11, unless I'm mistaken. Release 0.10.2 mentions that.

But for me it is not possible to install the module on V11 version
![image](https://github.com/sanguaire/fast-dice-box/assets/77894945/6d37f209-9a69-4694-b77f-9db7ece3e40e)

Is it possible that you need to declare version compatibility somewhere? It also says only version 10 - 10.291 are compatible on foundry website next to your module.

**Comment by sanguaire** [comment]
Fixed in new version. I removed the old version 0.91
