### ISSUE TITLE
BUG: Draggable button doesn't remember X coordinate

### ISSUE THREAD

**Issue by pesky-wobbit** [sanguaire/fast-dice-box#4]
Hopefully an easy fix. :)

**Comment by sanguaire** [comment]
Can you double check this in the settings of fast-dice-box? I didn't find this behavior in the code.

**Comment by pesky-wobbit** [comment]
Yes. When you drag the button from its starting position, the Y is updated in settings, but the X always returns to 100.

**Comment by pesky-wobbit** [comment]
You can update the X by entering a value in settings, but not by dragging.

**Comment by sanguaire** [comment]
Thanks. I will check it.

**Comment by sanguaire** [comment]
I released a update. Please check 😉

**Comment by pesky-wobbit** [comment]
Same behavior: can only change the X coordinate manually in settings - after dragging reverts to the old X coordinate.

**Comment by pesky-wobbit** [comment]
Tested on version fast dice v5.2

**Comment by sanguaire** [comment]
Can you uninstall and reinstall the module? I checked it several times and I can not get the same behavior.

**Comment by sanguaire** [comment]
Can check the values in the local storage of your browser? What are the values for fast-dice-box.left and fast-dice-box.top?

**Comment by pesky-wobbit** [comment]
uninstalled and reinstalled. How do I access the browsers local storage. F12 and ...?

**Comment by sanguaire** [comment]
Here the manual for chrome
https://developer.chrome.com/docs/devtools/storage/localstorage/

**Comment by pesky-wobbit** [comment]
Values precisely reflect those in settings. Left (x) is 1550 and top (y) is 20.

**Comment by sanguaire** [comment]
I can't replicate the bug. Maybe there is some cross module incompatibility. Which modules are installed? What foundry version you are using? On which browser the application is running? Can you test it with a complete new world aka no modules except fast dice roll installed? Can you send me the resulting html? Thanks in advance 🙂

**Comment by pesky-wobbit** [comment]
Works perfectly on new world as only mod! 
I'll post again if and when I determine the conflicting mod.

**Comment by pesky-wobbit** [comment]
The conflicting mod is: "Force Client Settings"
It's strange that it only interferes with the left (x-coordinate) setting.

**Comment by sanguaire** [comment]
Ok, thank you 👍. Will be fixed in my next version.

**Comment by sanguaire** [comment]
Fixed in v0.6
