### ISSUE TITLE
Installation Failed: Expected double-quoted property name in JSON at position 768

### ISSUE THREAD

**Issue by niuserre** [sanguaire/fast-dice-box#5]
![Screenshot 2023-01-06 173533](https://user-images.githubusercontent.com/1446741/211066649-9ff906c4-ae98-4184-942f-80a82b5de852.jpg)

Can't install 0.7. 
0.6.2 install works fine but can't update.

Foundry v10.291

![Screenshot 2023-01-06 173954](https://user-images.githubusercontent.com/1446741/211068003-60947922-1f48-4706-ac24-702fdda6e69a.jpg)

**Comment by sanguaire** [comment]
Fixed. Please try again.
