### ISSUE TITLE
Module.json using old syntax

### ISSUE THREAD

**Issue by Chronolegionnaire** [sanguaire/fast-dice-box#6]
![image](https://user-images.githubusercontent.com/69740347/211639071-f640964a-66a7-4289-9bf5-05bc076f4af8.png)

Really tiny inconsequential thing, but just wanted to make you aware if you weren't already.

**Comment by sanguaire** [comment]
Thanks. Will be fixed in the next version.

**Comment by sanguaire** [comment]
Fixed in version v0.8
