### ISSUE TITLE
REQUEST: Show/Hide Roll Mode Buttons Setting

### ISSUE THREAD

**Issue by pesky-wobbit** [sanguaire/fast-dice-box#7]
I rarely use the roll modes and would like to hide the little icons. A checkbox in settings would be great.
Thanks!

**Comment by sanguaire** [comment]
Implemented in v0.9

**Comment by pesky-wobbit** [comment]
It's not updating to 0.9.
Thanks!

**Comment by sanguaire** [comment]
Sorry, my fault. I forgot to register the release in foundry.

**Comment by pesky-wobbit** [comment]
Both features work well. Thank you!
